name: Run Tests
run-name: Testing ${{ github.ref_name }}
on: [push]
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   uses: actions/setup-python@v5
        -   name: Get FIREBASE_KEY.json
            run: echo "$FIREBASE_KEY" > FIREBASE_KEY.json
            env:
                FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        -   name: Run test.sh
            run: ./test.sh
